# Generated by Django 5.1.2 on 2024-11-04 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('exam_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exam_setting.examscategory')),
            ],
        ),
    ]
