# Generated by Django 5.1.2 on 2024-10-28 02:28

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('systemUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academic',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='administrator',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='admission',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='principal',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='academic',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='administrator',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='admission',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='principal',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='academic',
            name='academic_rank',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='courses_managed',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='id',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='id',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='admission_officer_id',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='department',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='id',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='office_contact',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='admission_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_authorized',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='login_token',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='leadership_level',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='office_hours',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AddField(
            model_name='academic',
            name='customuser_ptr',
            field=models.OneToOneField(auto_created=True, default='1', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systemUsers.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrator',
            name='administrator_id',
            field=models.CharField(default='1', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrator',
            name='customuser_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systemUsers.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='admission_id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='customuser_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systemUsers.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='principal',
            name='customuser_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systemUsers.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='customuser_ptr',
            field=models.OneToOneField(auto_created=True, default='1', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systemUsers.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='customuser_ptr',
            field=models.OneToOneField(auto_created=True, default='1', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systemUsers.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academic',
            name='academic_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Academic', 'Academic'), ('Admission', 'Admission'), ('Principal', 'Principal'), ('Administrator', 'Administrator')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='principal',
            name='principal_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
