# Generated by Django 5.1.2 on 2024-10-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemUsers', '0003_remove_administrator_customuser_ptr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='subject',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='full_name',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
