# Generated by Django 5.1.2 on 2024-11-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemUsers', '0004_rename_subject_teacherprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administratorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='admissionprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='principalprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AcademicProfile',
        ),
        migrations.DeleteModel(
            name='AdministratorProfile',
        ),
        migrations.DeleteModel(
            name='AdmissionProfile',
        ),
        migrations.DeleteModel(
            name='PrincipalProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
