# Generated by Django 5.1.2 on 2024-11-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemUsers', '0005_remove_administratorprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Enter a valid phone number.', max_length=15)),
                ('message', models.TextField(help_text='Enter the SMS content.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
