# Generated by Django 5.1.2 on 2024-10-29 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_entrycategory'),
        ('main_setting', '0010_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('other_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(default='Tanzania', max_length=50)),
                ('disability', models.CharField(choices=[('none', 'None'), ('skin', 'Skin'), ('hearing', 'Hearing'), ('vision', 'Vision'), ('other', 'Other')], default='none', max_length=10)),
                ('next_of_kin1_name', models.CharField(max_length=100)),
                ('next_of_kin1_mobile_number', models.CharField(max_length=15)),
                ('next_of_kin1_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('next_of_kin1_postal_address', models.CharField(blank=True, max_length=255, null=True)),
                ('next_of_kin2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin2_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('next_of_kin2_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('next_of_kin2_postal_address', models.CharField(blank=True, max_length=255, null=True)),
                ('next_of_kin2_profile_picture', models.ImageField(blank=True, null=True, upload_to='kin_pictures/')),
                ('entry_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.entrycategory')),
                ('entry_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_setting.class')),
                ('entry_programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_setting.programme')),
                ('entry_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_setting.term')),
                ('entry_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_setting.academicyear')),
                ('sponsor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.sponsor')),
            ],
        ),
    ]
