# Generated by Django 5.1.2 on 2024-10-29 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_importstudent'),
        ('main_setting', '0010_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgraded_students', to='main_setting.academicyear')),
                ('class_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgraded_students', to='main_setting.stream')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgraded_students', to='main_setting.programme')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgraded_students', to='main_setting.class')),
                ('students', models.ManyToManyField(related_name='upgrades', to='admission.studentregistration')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgraded_students', to='main_setting.term')),
            ],
        ),
    ]
