# Generated by Django 5.1.2 on 2024-10-29 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_upgradestudent'),
        ('main_setting', '0010_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upgradestudent',
            name='students',
        ),
        migrations.AlterField(
            model_name='upgradestudent',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_setting.academicyear'),
        ),
        migrations.AlterField(
            model_name='upgradestudent',
            name='class_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_setting.stream'),
        ),
        migrations.AlterField(
            model_name='upgradestudent',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_setting.programme'),
        ),
        migrations.AlterField(
            model_name='upgradestudent',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_setting.class'),
        ),
        migrations.AlterField(
            model_name='upgradestudent',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_setting.term'),
        ),
    ]
