# Generated by Django 5.1.2 on 2024-10-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_remove_upgradestudent_students_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upgradestudent',
            options={'verbose_name': 'Upgrade Student', 'verbose_name_plural': 'Upgrade Students'},
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='class_stream',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='term',
        ),
    ]
