# Generated by Django 5.1.2 on 2024-10-30 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_alter_upgradestudent_options_and_more'),
        ('main_setting', '0010_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upgradestudent',
            options={},
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='birth_date',
            field=models.DateField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='disability',
            field=models.CharField(choices=[('none', 'None'), ('skin', 'Skin'), ('hearing', 'Hearing'), ('vision', 'Vision'), ('other', 'Other')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='entry_category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='admission.entrycategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='entry_class',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main_setting.class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='entry_programme',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main_setting.programme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='entry_term',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main_setting.term'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='entry_year',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main_setting.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='first_name',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='1', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='last_name',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='nationality',
            field=models.CharField(default='Tanzania', max_length=50),
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='next_of_kin1_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='next_of_kin1_mobile_number',
            field=models.CharField(default='1', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='next_of_kin1_name',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='next_of_kin1_postal_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='next_of_kin2_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='next_of_kin2_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='next_of_kin2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='next_of_kin2_postal_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='next_of_kin2_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='kin_pictures/'),
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='other_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='registration_number',
            field=models.CharField(default='1', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upgradestudent',
            name='sponsor_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='admission.sponsor'),
            preserve_default=False,
        ),
    ]
