# Generated by Django 5.1.2 on 2024-10-31 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_alter_upgradestudent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistrationProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Student Registration Clone',
                'verbose_name_plural': 'Student Registration Clones',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admission.studentregistration',),
        ),
    ]
