# Generated by Django 5.1.2 on 2024-11-01 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_studentregistrationproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upgradestudent',
            options={'verbose_name': 'Upgrade Student', 'verbose_name_plural': 'Upgrade Students'},
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='entry_category',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='entry_class',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='entry_programme',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='entry_term',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='entry_year',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='next_of_kin1_email',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='next_of_kin1_mobile_number',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='next_of_kin1_name',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='next_of_kin1_postal_address',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='next_of_kin2_email',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='next_of_kin2_mobile_number',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='next_of_kin2_name',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='next_of_kin2_postal_address',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='next_of_kin2_profile_picture',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='other_name',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='upgradestudent',
            name='sponsor_name',
        ),
    ]
