# Generated by Django 5.1.2 on 2024-11-01 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0012_alter_upgradestudent_options_and_more'),
        ('main_setting', '0012_alter_class_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='stream_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_setting.stream'),
        ),
    ]
