# Generated by Django 5.1.2 on 2024-11-04 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0014_roomallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolContributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_for', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='admission.studentregistration')),
            ],
        ),
    ]
