# Generated by Django 5.1.2 on 2024-11-05 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0018_setsponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='sponsor_name',
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='physical_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='postal_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.setsponsor'),
        ),
    ]
