# Generated by Django 5.1.2 on 2024-11-05 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0019_remove_studentregistration_sponsor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='sponsor_name',
            field=models.ForeignKey(default='ALEX', on_delete=django.db.models.deletion.CASCADE, to='admission.sponsor'),
            preserve_default=False,
        ),
    ]
