# Generated by Django 5.1.2 on 2024-11-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0020_studentregistration_sponsor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setsponsor',
            name='sponsor_name',
            field=models.CharField(choices=[('government', 'Government'), ('ngos', 'NGOs')], max_length=50),
        ),
    ]
