# Generated by Django 5.1.2 on 2024-11-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0021_alter_setsponsor_sponsor_name'),
        ('main_setting', '0014_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='next_of_kin2_profile_picture',
            new_name='profile_picture',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='main_setting.subject'),
        ),
    ]
