# Generated by Django 5.1.2 on 2024-11-10 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0022_rename_next_of_kin2_profile_picture_studentregistration_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentregistrationproxy',
            options={'verbose_name': 'Upgrade Students', 'verbose_name_plural': 'Upgrade Students'},
        ),
    ]
