# Generated by Django 5.1.2 on 2024-11-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0024_studentregistration_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
