# Generated by Django 5.1.2 on 2024-11-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0025_alter_sponsor_sponsor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='physical_address',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='postal_address',
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_name',
            field=models.CharField(choices=[('government', 'Government'), ('ngo', 'Non-Government Organization')], default='NGO', max_length=50),
            preserve_default=False,
        ),
    ]
