# Generated by Django 5.1.2 on 2024-11-29 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0027_alter_studentregistration_subjects'),
        ('main_setting', '0019_delete_studentsresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='stream_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main_setting.stream'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='subjects',
            field=models.ManyToManyField(to='main_setting.subject'),
        ),
    ]
