# Generated by Django 5.1.2 on 2024-11-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_attendance', '0001_initial'),
        ('admission', '0013_studentregistration_stream_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordAttendanceProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Record Attendance',
                'verbose_name_plural': 'Record Attendance',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admission.studentregistration',),
        ),
    ]
