# Generated by Django 5.1.2 on 2024-11-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_attendance', '0003_studentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='upload_assignment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
    ]
