# Generated by Django 5.1.2 on 2024-11-14 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_attendance', '0004_studentassignment_upload_assignment'),
        ('admission', '0026_remove_sponsor_email_remove_sponsor_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student_attendance.absentreason')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.studentregistration')),
            ],
        ),
    ]
