# Generated by Django 5.1.2 on 2024-11-16 01:27

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0026_remove_sponsor_email_remove_sponsor_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Students',
                'verbose_name_plural': 'Students',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admission.studentregistration',),
        ),
    ]
