# Generated by Django 5.1.2 on 2024-11-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentproxy',
            options={'verbose_name': 'My details', 'verbose_name_plural': 'My details'},
        ),
    ]
