# Generated by Django 5.1.2 on 2024-10-25 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_setting', '0002_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='subjects_count',
        ),
    ]
