# Generated by Django 5.1.2 on 2024-10-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_setting', '0003_remove_stream_subjects_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='name_of_streams',
        ),
        migrations.RemoveField(
            model_name='class',
            name='no_of_streams',
        ),
        migrations.RemoveField(
            model_name='class',
            name='program_name',
        ),
        migrations.AddField(
            model_name='class',
            name='assigned_streams',
            field=models.ManyToManyField(blank=True, related_name='classes', to='main_setting.stream'),
        ),
        migrations.AddField(
            model_name='class',
            name='no_of_stream',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='class',
            name='programme',
            field=models.CharField(default='A-LEVEL', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=100),
        ),
    ]
