# Generated by Django 5.1.2 on 2024-10-25 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_setting', '0004_remove_class_name_of_streams_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_assigned_subjects', models.PositiveIntegerField(default=0, editable=False)),
                ('assigned_streams', models.ManyToManyField(blank=True, related_name='subject_configs', to='main_setting.stream')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_configs', to='main_setting.class')),
                ('subjects', models.ManyToManyField(blank=True, related_name='subject_configs', to='main_setting.subject')),
            ],
        ),
    ]
