# Generated by Django 5.1.2 on 2024-10-28 13:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_setting', '0007_subjectallocation'),
        ('systemUsers', '0004_rename_subject_teacherprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectallocation',
            options={},
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='assigned_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='phone_number',
            field=models.CharField(default='1', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='subjectallocation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemUsers.teacherprofile'),
        ),
    ]
