# Generated by Django 5.1.2 on 2024-10-28 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_setting', '0008_alter_subjectallocation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_date', models.DateField()),
                ('program_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_setting.programme')),
            ],
        ),
    ]
