# Generated by Django 5.1.2 on 2024-11-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_setting', '0010_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectallocation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
