# Generated by Django 5.1.2 on 2024-11-01 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_setting', '0011_alter_subjectallocation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_setting.programme'),
        ),
    ]
