# Generated by Django 5.1.2 on 2024-11-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_setting', '0013_publish_published_by_publish_published_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
