# Generated by Django 5.1.2 on 2024-11-10 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_setting', '0014_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish',
            name='action',
        ),
        migrations.RemoveField(
            model_name='publish',
            name='published_by',
        ),
        migrations.RemoveField(
            model_name='publish',
            name='published_date',
        ),
    ]
