# Generated by Django 5.1.2 on 2024-11-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_setting', '0015_remove_publish_action_remove_publish_published_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
