# Generated by Django 5.1.2 on 2024-11-14 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_setting', '0016_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectallocation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_setting.teacher'),
        ),
    ]
