# Generated by Django 5.1.2 on 2024-11-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_setting', '0017_alter_subjectallocation_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=100)),
                ('reg_number', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('mt3', models.FloatField()),
                ('mt4', models.FloatField()),
                ('mt2', models.FloatField()),
                ('ae', models.FloatField()),
                ('hpbt2', models.FloatField()),
                ('average', models.FloatField()),
                ('grade', models.CharField(max_length=2)),
                ('remark', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
            ],
        ),
    ]
