# Generated by Django 5.1.2 on 2024-11-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_setting', '0018_studentsresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentsResult',
        ),
    ]
