# Generated by Django 5.1.2 on 2024-11-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Annual report',
                'verbose_name_plural': 'Annual report',
            },
        ),
        migrations.CreateModel(
            name='ProgressReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Progress report',
                'verbose_name_plural': 'Progress report',
            },
        ),
        migrations.CreateModel(
            name='SubjectReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Subject report',
                'verbose_name_plural': 'Subject report',
            },
        ),
        migrations.CreateModel(
            name='TermReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Term report',
                'verbose_name_plural': 'Term report',
            },
        ),
    ]
