# Generated by Django 5.1.2 on 2024-11-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_delete_progressreports_progressreports'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassessment',
            name='registration_number',
            field=models.CharField(default='0001', max_length=50),
            preserve_default=False,
        ),
    ]
