# Generated by Django 5.1.2 on 2024-11-14 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_setting', '0002_setexam'),
        ('reports', '0006_alter_studentassessment_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassessment',
            name='assessment_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_setting.gradescale'),
        ),
    ]
